name: Tests

on:
  pull_request:
    branches: [main, prod]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: install staticcheck
        run: |
          cd /tmp && go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: install govulncheck
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Make tests
        env:
          GOFLAGS: -mod=vendor
        run: |
          make
